apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ${CLUSTER_NAME}
    machine.openshift.io/cluster-api-machine-role: workload
    machine.openshift.io/cluster-api-machine-type: workload
  name: ${CLUSTER_NAME}-workload
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ${CLUSTER_NAME}
      machine.openshift.io/cluster-api-machineset: ${CLUSTER_NAME}-workload
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ${CLUSTER_NAME}
        machine.openshift.io/cluster-api-machine-role: workload
        machine.openshift.io/cluster-api-machine-type: workload
        machine.openshift.io/cluster-api-machineset: ${CLUSTER_NAME}-workload
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/workload: ""
      providerSpec:
        value:
          apiVersion: openstackproviderconfig.openshift.io/v1alpha1
          cloudName: openstack
          cloudsSecret:
            name: openstack-cloud-credentials
            namespace: openshift-machine-api
          flavor: ${OPENSHIFT_WORKLOAD_NODE_INSTANCE_TYPE}
          image: ${CLUSTER_NAME}-rhcos
          kind: OpenstackProviderSpec
          networks:
          - filter: {}
            subnets:
            - filter:
                name: ${CLUSTER_NAME}-nodes
                tags: openshiftClusterID=${CLUSTER_NAME}
          securityGroups:
          - filter: {}
            name: ${CLUSTER_NAME}-worker
          serverMetadata:
            Name: ${CLUSTER_NAME}-worker
            openshiftClusterID: ${CLUSTER_NAME}
          tags:
          - openshiftClusterID=${CLUSTER_NAME}
          trunk: true
          userDataSecret:
            name: worker-user-data